<?php
/*
Ad Injection config file dbversion=24
DO NOT EDIT MANUALLY
This file is generated by Ad Injection
*/

function adinj_config_allow_referrers() { return false; }
function adinj_config_allowed_referrers_list() { return array('.google.', '.bing.', '.yahoo.', '.ask.', 'search?', 'search.'); }

function adinj_config_block_ips() { return false; }
function adinj_config_blocked_ips_list() { return array(); }

function adinj_config_block_referrers() { return false; }
function adinj_config_blocked_referrers_list() { return array(); }
function adinj_config_block_hours() { return 24; }

function adinj_config_block_after_ad_click() { return false; }

function adinj_config_debug_mode() { return false; }

?>